name: ESLint

on:
  push:
    branches: [ main ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '18.13.0'

      - name: Run Prettier and ESLint Check For Frontend
        env:
          NODE_ENV: development
        run: |
          cd subfolder
          npm i
          npm run eslint:check